// src/components/features/player/BulkPlayerUploadModal.jsx
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FaTimes, FaUpload, FaFileExcel, FaDownload, FaCheck, FaExclamationTriangle } from 'react-icons/fa';
import { toast } from 'react-toastify';

export default function BulkPlayerUploadModal({ isOpen, onClose, onSubmit, onUploaded, schools = [] }) {
  const [file, setFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [uploadResult, setUploadResult] = useState(null);
  const [errors, setErrors] = useState([]);

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];
    setFile(selectedFile);
    setUploadResult(null);
    setErrors([]);
  };

  const parseCSV = (csvText) => {
    const lines = csvText.split('\n').filter(line => line.trim());
    if (lines.length < 2) {
      throw new Error('CSV file must have at least a header row and one data row');
    }

    const headers = lines[0].split(',').map(h => h.trim().replace(/"/g, ''));
    const athletes = [];

    for (let i = 1; i < lines.length; i++) {
      const values = lines[i].split(',').map(v => v.trim().replace(/"/g, ''));
      if (values.length !== headers.length) {
        continue; // Skip malformed rows
      }

      const athlete = {};
      headers.forEach((header, index) => {
        const value = values[index];
        
        // Map CSV headers to expected field names
        switch (header.toLowerCase()) {
          case 'name':
          case 'full_name':
            athlete.full_name = value;
            break;
          case 'email':
          case 'guardian_email':
            athlete.guardian_email = value;
            break;
          case 'phone':
          case 'guardian_phone':
            athlete.guardian_phone = value;
            break;
          case 'school_id':
            athlete.school_id = parseInt(value) || null;
            break;
          case 'player_id':
          case 'athlete_id':
            // Skip athlete_id - it's auto-generated by the backend
            break;
          case 'date_of_birth':
          case 'dob':
            // Convert date from DD/MM/YYYY to YYYY-MM-DD format
            if (value) {
              const dateParts = value.split('/');
              if (dateParts.length === 3) {
                const [day, month, year] = dateParts;
                athlete.date_of_birth = `${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}`;
              } else {
                athlete.date_of_birth = value; // Keep original if not in expected format
              }
            }
            break;
          case 'gender':
            athlete.gender = value.charAt(0).toUpperCase() + value.slice(1).toLowerCase();
            break;
          case 'sport':
          case 'primary_sport':
            athlete.primary_sport = value;
            break;
          case 'guardian_name':
            athlete.guardian_name = value;
            break;
          case 'nationality':
            athlete.nationality = value || 'Nepali';
            break;
          case 'grade':
            athlete.grade = value;
            break;
          case 'section':
            athlete.section = value;
            break;
          default:
            // Handle other fields
            athlete[header] = value;
        }
      });

      // Set default values for required fields
      if (!athlete.nationality) athlete.nationality = 'Nepali';
      if (!athlete.gender) athlete.gender = 'Male';
      
      athletes.push(athlete);
    }

    return athletes;
  };

  const handleUpload = async () => {
    if (!file) {
      toast.error('Please select a file first');
      return;
    }

    setLoading(true);

    try {
      // Read and parse the CSV file
      const fileText = await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = (e) => resolve(e.target.result);
        reader.onerror = (e) => reject(new Error('Failed to read file'));
        reader.readAsText(file);
      });

      // Parse CSV to athletes data
      const athletesData = parseCSV(fileText);
      
      if (athletesData.length === 0) {
        throw new Error('No valid athlete data found in the file');
      }

      console.log('Parsed athletes data:', athletesData);

      // Submit the parsed data
      if (onSubmit) {
        const result = await onSubmit(athletesData);
        
        setUploadResult({ 
          success: true, 
          message: `Successfully processed ${athletesData.length} athletes. ${result.success_count || 0} created, ${result.error_count || 0} errors.`
        });
        
        if (result.errors && result.errors.length > 0) {
          const formattedErrors = result.errors.map(err => {
            if (typeof err.errors === 'object') {
              // Handle detailed field errors
              const fieldErrors = Object.entries(err.errors).map(([field, fieldError]) => {
                const errorList = Array.isArray(fieldError) ? fieldError : [fieldError];
                return `${field}: ${errorList.join(', ')}`;
              }).join('; ');
              return `Row ${err.index + 2} (${err.name}): ${fieldErrors}`;
            } else {
              return `Row ${err.index + 2} (${err.name}): ${err.errors}`;
            }
          });
          setErrors(formattedErrors);
        }
        
        setFile(null);
        
        // Call onUploaded callback to refresh data
        if (onUploaded) {
          onUploaded();
        }
      }
    } catch (error) {
      console.error('Upload error:', error);
      console.error('Error response data:', error.response?.data);
      
      const errorMessage = error.message || 'Upload failed';
      setUploadResult({ success: false, message: errorMessage });
      
      // Handle different types of errors
      let formattedErrors = [];
      
      if (error.response?.data) {
        const responseData = error.response.data;
        
        // Check for pre-formatted errors first
        if (responseData.formatted_errors && Array.isArray(responseData.formatted_errors)) {
          formattedErrors = responseData.formatted_errors;
        } else if (responseData.errors) {
          const errorData = responseData.errors;
          
          if (errorData.athletes) {
            // Handle validation errors for individual athletes
            errorData.athletes.forEach((athleteErrors, index) => {
              if (athleteErrors && typeof athleteErrors === 'object') {
                Object.entries(athleteErrors).forEach(([field, fieldErrors]) => {
                  const errorList = Array.isArray(fieldErrors) ? fieldErrors : [fieldErrors];
                  errorList.forEach(err => {
                    formattedErrors.push(`Row ${index + 2}, ${field}: ${err}`);
                  });
                });
              }
            });
          } else if (Array.isArray(errorData)) {
            // Handle array of errors
            formattedErrors = errorData.map(err => 
              typeof err === 'string' ? err : JSON.stringify(err)
            );
          } else if (typeof errorData === 'object') {
            // Handle object errors (field-level validation)
            Object.entries(errorData).forEach(([field, fieldErrors]) => {
              const errorList = Array.isArray(fieldErrors) ? fieldErrors : [fieldErrors];
              errorList.forEach(err => {
                formattedErrors.push(`${field}: ${err}`);
              });
            });
          }
        }
        
        // If no specific errors found, try to extract from message or other fields
        if (formattedErrors.length === 0) {
          if (responseData.message && responseData.message !== errorMessage) {
            formattedErrors.push(responseData.message);
          }
          if (responseData.detail) {
            formattedErrors.push(responseData.detail);
          }
        }
      }
      
      // Fallback to generic error message
      if (formattedErrors.length === 0) {
        formattedErrors = [errorMessage];
      }
      
      setErrors(formattedErrors);
      toast.error(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const downloadTemplate = () => {
    // Create CSV template with required and optional fields
    const headers = [
      'full_name', 'athlete_id', 'date_of_birth', 'gender', 'school_id',
      'guardian_name', 'guardian_phone', 'guardian_email', 'nationality',
      'grade', 'section', 'primary_sport', 'address', 'province', 'district'
    ];
    
    const sampleRows = [
      [
        'John Doe', 'ATH001', '15/01/2005', 'Male', '4',
        'Jane Doe', '+977-9841234567', 'jane.doe@example.com', 'Nepali',
        '10', 'A', 'Football', 'Kathmandu', 'Bagmati', 'Kathmandu'
      ],
      [
        'Mary Smith', 'ATH002', '22/03/2006', 'Female', '2',
        'Robert Smith', '+977-9851234567', 'robert.smith@example.com', 'Nepali',
        '9', 'B', 'Basketball', 'Pokhara', 'Gandaki', 'Kaski'
      ]
    ];
    
    const csvContent = [
      headers.join(','),
      ...sampleRows.map(row => row.join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'athlete_upload_template.csv';
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const handleClose = () => {
    setFile(null);
    setUploadResult(null);
    setErrors([]);
    onClose();
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          <motion.div
            className="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto"
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.9, opacity: 0 }}
          >
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center">
                <FaUpload className="mr-2 text-blue-500" />
                Bulk Player Upload
              </h2>
              <button
                onClick={handleClose}
                className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
              >
                <FaTimes size={24} />
              </button>
            </div>

            {/* Instructions */}
            <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg mb-6">
              <h3 className="font-semibold text-blue-800 dark:text-blue-300 mb-2">
                Upload Instructions
              </h3>
              <ul className="text-sm text-blue-700 dark:text-blue-300 space-y-1">
                <li>• Download the template CSV file to see the required format</li>
                <li>• <strong>Required fields:</strong> full_name, athlete_id, date_of_birth, gender, school_id</li>
                <li>• <strong>Optional fields:</strong> guardian info, address, grade, section, sport</li>
                <li>• Ensure school_id corresponds to existing schools</li>
                <li>• <strong>Available School IDs:</strong> 2, 3, 4, 5, 6</li>
                <li>• Date format should be YYYY-MM-DD (e.g., 2005-01-15)</li>
                <li>• Gender should be: Male, Female, or Other (case-sensitive)</li>
                <li>• Athlete ID must be unique for each player</li>
              </ul>
            </div>

            {/* Template Download */}
            <div className="mb-6">
              <button
                onClick={downloadTemplate}
                className="flex items-center px-4 py-2 bg-green-500 text-white rounded-md hover:bg-green-600 transition-colors"
              >
                <FaDownload className="mr-2" />
                Download Template
              </button>
            </div>

            {/* File Upload */}
            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Select CSV File
              </label>
              <div className="flex items-center space-x-4">
                <input
                  type="file"
                  accept=".csv,.xlsx,.xls"
                  onChange={handleFileChange}
                  className="flex-1 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
                />
                {file && (
                  <div className="flex items-center text-green-600 dark:text-green-400">
                    <FaFileExcel className="mr-1" />
                    <span className="text-sm">{file.name}</span>
                  </div>
                )}
              </div>
            </div>

            {/* Upload Result */}
            {uploadResult && (
              <div className={`p-4 rounded-lg mb-6 ${
                uploadResult.success 
                  ? 'bg-green-50 dark:bg-green-900/20 text-green-800 dark:text-green-300' 
                  : 'bg-red-50 dark:bg-red-900/20 text-red-800 dark:text-red-300'
              }`}>
                <div className="flex items-center">
                  {uploadResult.success ? (
                    <FaCheck className="mr-2" />
                  ) : (
                    <FaExclamationTriangle className="mr-2" />
                  )}
                  <span className="font-semibold">{uploadResult.message}</span>
                </div>
              </div>
            )}

            {/* Errors */}
            {errors.length > 0 && (
              <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg mb-6">
                <h4 className="font-semibold text-red-800 dark:text-red-300 mb-3 flex items-center">
                  <FaExclamationTriangle className="mr-2" />
                  Validation Errors ({errors.length}):
                </h4>
                <div className="max-h-48 overflow-y-auto">
                  <ul className="text-sm text-red-700 dark:text-red-300 space-y-2">
                    {errors.map((error, index) => (
                      <li key={index} className="flex items-start">
                        <span className="text-red-500 mr-2 mt-0.5">•</span>
                        <span className="flex-1 font-mono text-xs bg-red-100 dark:bg-red-800/30 px-2 py-1 rounded">
                          {error}
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="mt-3 text-xs text-red-600 dark:text-red-400">
                  <strong>Tip:</strong> Fix the errors in your CSV file and try uploading again.
                </div>
              </div>
            )}

            {/* School Reference */}
            {schools.length > 0 && (
              <div className="bg-gray-50 dark:bg-gray-700/50 p-4 rounded-lg mb-6">
                <h4 className="font-semibold text-gray-800 dark:text-gray-300 mb-2">
                  Available Schools (use these IDs):
                </h4>
                <div className="max-h-32 overflow-y-auto">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-sm">
                    {schools.map(school => (
                      <div key={school.school_id || school.id} className="flex justify-between text-gray-700 dark:text-gray-300">
                        <span className="truncate mr-2">{school.name}</span>
                        <span className="font-mono text-blue-600 dark:text-blue-400">ID: {school.school_id || school.id}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* Actions */}
            <div className="flex justify-end space-x-4">
              <button
                onClick={handleClose}
                className="px-4 py-2 text-gray-600 dark:text-gray-400 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700"
              >
                Cancel
              </button>
              <button
                onClick={handleUpload}
                disabled={!file || loading}
                className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed flex items-center"
              >
                {loading ? (
                  <>
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                      className="w-4 h-4 border-2 border-white border-t-transparent rounded-full mr-2"
                    />
                    Uploading...
                  </>
                ) : (
                  <>
                    <FaUpload className="mr-2" />
                    Upload Players
                  </>
                )}
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
