# Generated by Django 5.2.4 on 2025-09-03 16:43

import apps.athletes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athlete_address_athlete_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete_id',
            field=models.CharField(default=apps.athletes.models.generate_athlete_id, editable=False, max_length=5, unique=True),
        ),
    ]
