# Generated by Django 5.2.4 on 2025-09-05 06:04

import apps.athletes.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_alter_athlete_athlete_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='birth_certificate',
            field=models.FileField(blank=True, help_text='Birth certificate (PDF, JPG, PNG, DOC, DOCX - Max 10MB)', null=True, upload_to=apps.athletes.models.athlete_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='athlete',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo (JPG, PNG, GIF - Max 5MB)', null=True, upload_to=apps.athletes.models.athlete_profile_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='athlete_id',
            field=models.CharField(default=apps.athletes.models.generate_athlete_id, editable=False, max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='AthleteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('citizenship', 'Citizenship Document'), ('passport', 'Passport'), ('school_id', 'School ID'), ('medical_certificate', 'Medical Certificate'), ('photo_id', 'Photo ID'), ('other', 'Other Document')], default='other', max_length=50)),
                ('file', models.FileField(help_text='Document file (PDF, JPG, PNG, DOC, DOCX - Max 10MB)', upload_to=apps.athletes.models.athlete_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('requires_review', 'Requires Manual Review')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='athletes.athlete')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_athlete_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'athlete_documents',
                'ordering': ['-created_at'],
                'unique_together': {('athlete', 'document_type', 'file')},
            },
        ),
    ]
