# Generated by Django 5.2.4 on 2025-09-03 04:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Official name of the organization', max_length=255)),
                ('type', models.CharField(choices=[('sports_club', 'Sports Club'), ('academy', 'Sports Academy'), ('training_center', 'Training Center'), ('federation', 'Sports Federation'), ('association', 'Sports Association'), ('league', 'Sports League'), ('other', 'Other')], default='sports_club', help_text='Type of sports organization', max_length=50)),
                ('registration_number', models.CharField(help_text='Official registration number', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the organization')),
                ('contact_person', models.CharField(help_text='Name of primary contact person', max_length=255)),
                ('email', models.EmailField(help_text='Primary email address', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('secondary_phone', models.CharField(blank=True, help_text='Secondary phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(help_text='Complete address')),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', help_text='Verification status', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date when organization was verified', null=True)),
                ('founded_date', models.DateField(blank=True, help_text='Date when organization was founded', null=True)),
                ('website', models.URLField(blank=True, help_text='Organization website')),
                ('logo', models.ImageField(blank=True, help_text='Organization logo', upload_to='organizations/logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the organization is active')),
                ('can_create_tournaments', models.BooleanField(default=True, help_text='Whether organization can create tournaments')),
                ('can_register_athletes', models.BooleanField(default=True, help_text='Whether organization can register athletes')),
                ('admin_user', models.OneToOneField(help_text='User account for organization administrator', on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin user who verified this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about the athlete registration')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_registrations', to='athletes.athlete')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_athletes', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Athlete',
                'verbose_name_plural': 'Organization Athletes',
                'db_table': 'organization_athletes',
                'unique_together': {('organization', 'athlete')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationSchoolPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partnership_type', models.CharField(choices=[('training', 'Training Partnership'), ('sponsorship', 'Sponsorship'), ('collaboration', 'Collaboration'), ('affiliate', 'Affiliate Program')], default='collaboration', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the partnership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_partnerships', to='organizations.organization')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_partnerships', to='schools.school')),
            ],
            options={
                'verbose_name': 'Organization-School Partnership',
                'verbose_name_plural': 'Organization-School Partnerships',
                'db_table': 'organization_school_partnerships',
                'unique_together': {('organization', 'school')},
            },
        ),
    ]
