# Generated by Django 5.2.4 on 2025-08-22 10:22

import apps.documents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('guardians', '__first__'),
        ('schools', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('certificate', 'Certificate'), ('scoresheet', 'Scoresheet'), ('athlete_photo', 'Athlete Photo'), ('guardian_document', 'Guardian Document'), ('school_document', 'School Document'), ('tournament_document', 'Tournament Document'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to=apps.documents.models.upload_to_documents, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif'])])),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_result', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guardians.guardian')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('ocr_id', models.AutoField(primary_key=True, serialize=False)),
                ('extracted_text', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('language_detected', models.CharField(default='en', max_length=10)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='documents.document')),
            ],
            options={
                'db_table': 'ocr_results',
            },
        ),
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('scoresheet', 'Scoresheet'), ('certificate', 'Certificate'), ('report', 'Report'), ('custom', 'Custom')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('template_file', models.FileField(upload_to='pdf_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html', 'json'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('pdf_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='generated_pdfs/')),
                ('generation_data', models.JSONField(default=dict)),
                ('file_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.pdftemplate')),
            ],
            options={
                'db_table': 'generated_pdfs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.documents.models.upload_to_images)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('file_size', models.PositiveIntegerField()),
                ('quality', models.PositiveIntegerField(default=85)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to='documents.document')),
            ],
            options={
                'db_table': 'processed_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
