# Generated by Django 5.2.4 on 2025-08-22 08:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tournament_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sport', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('school', 'School'), ('district', 'District'), ('provincial', 'Provincial'), ('national', 'National'), ('international', 'International')], default='school', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True)),
                ('min_teams', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)])),
                ('max_players_per_team', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('organizer_type', models.CharField(blank=True, choices=[('school', 'School'), ('district', 'District'), ('national', 'National'), ('other', 'Other')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='upcoming', max_length=20)),
                ('format', models.CharField(blank=True, choices=[('knockout', 'Knockout'), ('league', 'League'), ('group_stage', 'Group Stage'), ('round_robin', 'Round Robin'), ('double_elimination', 'Double Elimination')], max_length=50, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('prize_details', models.TextField(blank=True, null=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('sports_config', models.JSONField(blank=True, default=list)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('age_group', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
                ('organizer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentSport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('age_group', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], max_length=20, null=True)),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True)),
                ('min_teams', models.PositiveIntegerField(default=2)),
                ('players_per_team', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, choices=[('knockout', 'Knockout'), ('league', 'League'), ('group_stage', 'Group Stage'), ('round_robin', 'Round Robin'), ('double_elimination', 'Double Elimination')], max_length=50, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('prize_details', models.TextField(blank=True, null=True)),
                ('sport_config', models.JSONField(blank=True, default=dict)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_sports',
            },
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.PositiveIntegerField()),
                ('team_name', models.CharField(max_length=200)),
                ('school_id', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('seed_order', models.PositiveIntegerField(blank=True, null=True)),
                ('group_assignment', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('registration_data', models.JSONField(blank=True, default=dict)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_teams', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_teams',
                'ordering': ['seed_order', 'registration_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.PositiveIntegerField()),
                ('player_name', models.CharField(max_length=200)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_vice_captain', models.BooleanField(default=False)),
                ('is_eligible', models.BooleanField(default=True)),
                ('eligibility_notes', models.TextField(blank=True, null=True)),
                ('registration_data', models.JSONField(blank=True, default=dict)),
                ('tournament_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.tournamentteam')),
            ],
            options={
                'db_table': 'tournament_players',
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['sport'], name='tournaments_sport_9775d9_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status'], name='tournaments_status_2bfcdf_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['start_date', 'end_date'], name='tournaments_start_d_16177d_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['organizer_type', 'organizer_id'], name='tournaments_organiz_20141b_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['tournament_code'], name='tournaments_tournam_c9b4af_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['level'], name='tournaments_level_ae9e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentsport',
            index=models.Index(fields=['tournament', 'sport_name'], name='tournament__tournam_46487e_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentsport',
            index=models.Index(fields=['sport_name', 'category'], name='tournament__sport_n_46cda1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentsport',
            unique_together={('tournament', 'sport_name', 'category', 'age_group', 'gender')},
        ),
        migrations.AddIndex(
            model_name='tournamentteam',
            index=models.Index(fields=['tournament', 'registration_status'], name='tournament__tournam_d367fe_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentteam',
            index=models.Index(fields=['team_id'], name='tournament__team_id_e7a22d_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentteam',
            index=models.Index(fields=['school_id'], name='tournament__school__068d37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together={('tournament', 'team_id')},
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['tournament_team', 'is_eligible'], name='tournament__tournam_c61117_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['player_id'], name='tournament__player__abda9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together={('tournament_team', 'player_id')},
        ),
    ]
