# Generated by Django 5.2.4 on 2025-08-22 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('query', models.CharField(max_length=500)),
                ('place_id', models.CharField(max_length=100, unique=True)),
                ('formatted_address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('location_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'location_cache',
                'indexes': [models.Index(fields=['query'], name='location_ca_query_6f99f2_idx'), models.Index(fields=['place_id'], name='location_ca_place_i_e633ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_text', models.TextField()),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'translation_cache',
                'indexes': [models.Index(fields=['source_language', 'target_language'], name='translation_source__d396d2_idx')],
                'unique_together': {('source_text', 'source_language', 'target_language')},
            },
        ),
        migrations.CreateModel(
            name='GoogleServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.CharField(choices=[('vision', 'Google Vision API'), ('translate', 'Google Translate API'), ('maps', 'Google Maps API')], max_length=20)),
                ('operation', models.CharField(max_length=100)),
                ('request_count', models.IntegerField(default=1)),
                ('response_size', models.IntegerField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_service_usage',
                'indexes': [models.Index(fields=['service_type', 'created_at'], name='google_serv_service_7f210d_idx'), models.Index(fields=['user', 'created_at'], name='google_serv_user_id_1f16e3_idx')],
            },
        ),
    ]
