# Generated by Django 5.2.4 on 2025-08-22 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_registration', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both'), ('none', 'None')], default='both', max_length=10)),
                ('athlete_registration', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both'), ('none', 'None')], default='both', max_length=10)),
                ('tournament_updates', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both'), ('none', 'None')], default='email', max_length=10)),
                ('reminders', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both'), ('none', 'None')], default='both', max_length=10)),
                ('marketing', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both'), ('none', 'None')], default='none', max_length=10)),
                ('preferred_email', models.EmailField(blank=True, max_length=254)),
                ('preferred_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('category', models.CharField(choices=[('guardian_registration', 'Guardian Registration'), ('athlete_registration', 'Athlete Registration'), ('tournament_notification', 'Tournament Notification'), ('school_notification', 'School Notification'), ('reminder', 'Reminder'), ('verification', 'Verification'), ('welcome', 'Welcome'), ('password_reset', 'Password Reset')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'unique_together': {('template_type', 'category')},
            },
        ),
        migrations.CreateModel(
            name='GuardianClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('claim_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_approval', 'Pending Approval'), ('pending_school_approval', 'Pending School Approval'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('requires_school_approval', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_claims', to='athletes.athlete')),
            ],
            options={
                'db_table': 'guardian_claims',
                'indexes': [models.Index(fields=['claim_code'], name='guardian_cl_claim_c_1470da_idx'), models.Index(fields=['status'], name='guardian_cl_status_17498b_idx'), models.Index(fields=['expires_at'], name='guardian_cl_expires_670490_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notification_logs',
                'indexes': [models.Index(fields=['notification_type', 'status'], name='notificatio_notific_250714_idx'), models.Index(fields=['recipient_email'], name='notificatio_recipie_20e31c_idx'), models.Index(fields=['recipient_phone'], name='notificatio_recipie_3c1ea6_idx'), models.Index(fields=['created_at'], name='notificatio_created_45a1e0_idx')],
            },
        ),
    ]
