# Generated by Django 5.2.4 on 2025-08-22 09:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_code', models.CharField(help_text='Unique school code for identification', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Official school name', max_length=255)),
                ('address', models.TextField(help_text='Complete school address')),
                ('country', models.CharField(default='Rwanda', max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('ward', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('website', models.URLField(blank=True, null=True)),
                ('principal_name', models.CharField(max_length=255)),
                ('onboarding_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('admin_user', models.OneToOneField(help_text='The user who administers this school', on_delete=django.db.models.deletion.CASCADE, related_name='administered_school', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code for the house', max_length=7)),
                ('points', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='schools.school')),
            ],
            options={
                'db_table': 'school_houses',
                'ordering': ['-points', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('read_status', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schools.school')),
            ],
            options={
                'db_table': 'school_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('Sports Coordinator', 'Sports Coordinator'), ('Teacher', 'Teacher'), ('Coach', 'Coach'), ('Administrator', 'Administrator'), ('Other', 'Other')], max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='schools.school')),
            ],
            options={
                'db_table': 'school_staff',
                'ordering': ['position', 'full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['school_code'], name='schools_school__3ec92c_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='schools_name_2838ce_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['province', 'district'], name='schools_provinc_a48fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['onboarding_status'], name='schools_onboard_015847_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolhouse',
            unique_together={('school', 'name')},
        ),
    ]
