# Generated by Django 5.2.4 on 2025-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='School logo image', null=True, upload_to='school_logos/'),
        ),
    ]
